const tour = [
    { package_states: 'pending', tourTitle: "Sylhet tour", price: '5,000', description: 'Sylhet tour is now easier than ever with the guides provided on this website. Beautiful Sylhet City is located in north- eastern Bangladesh on the bank of River Surma.Travellers can easily reach Sylhet by Air, Train or Bus, departing daily several times from and to Dhaka, as well as Chittagong. We provide tourist information to help one plan their perfect vacation in Sylhet, from maps/directions to recommending delicious  restaurants and finding one perfect accommodations in Sylhet Travellers can easily reach Sylhet by Air, Train or Bus, departing daily several times from and to Dhaka, as well as Chittagong.', img: "" },
    { tourTitle: 'Thailand tour', package_states: 'pending', price: '25,000', description: 'About Thailand Holidays - There’s a reason why Thailand is such a popular vacation destination. It’s exotic and affordable and it’s no wonder why so many people prefer to go on a Thailand Trip whenever they get a vacation.The good news is that with Thomas Cook India’s Thailand Holiday Packages, you’ll get a lot more than you bargained for. Don’t believe us? Just check the Thomas Cook website and you’ll be pleasantly surprised at the variety that’s on offer, both in terms of budget and duration of stay among the many Thailand Tour Packages. From 5 nights 6 days to as long as 10 nights 11 days, there’s the perfect Thailand Tour just for you on the Thomas Cook India website. Even budget-wise there’s a lot of flexibility with rates starting as low as INR 17 237.00 to the more expensive   days that go up to INR 128 020.00 which is still quite reasonable, considering just how much you will get to see and experience during your Thailand Holiday.', img: 'https://i.ibb.co/dWMPkg6/Thailand.jpg' },
    { tourTitle: 'Darjiling', package_states: 'pending', price: '15,000', description: 'Situated in the Jalpaiguri and Siliguri districts of West Bengal, Siliguri is a city known as the Gateway to North-East India.Located 560 kms from Kolkata to the north, Siliguri is the twin city of Jalpaiguri and the third largest in West Bengal.Siliguri has its own international airport which serves mainly as a base for tourists to camp in before moving out to explore  nearby tourist attractions such as Kalimpong, Darjeeling, Gangtok and Bhutan. However, Siliguri itself is a perfectly good holiday destination, with sufficient things to see and do. Over the years, Siliguri has become famous for its products such as tea and timber and also an important commercial and connecting hub', img: 'https://i.ibb.co/4W77qSw/Darjieeling.jpg' },
    { tourTitle: 'Dhaka - Kathmandu', package_states: 'pending', price: '20,000', description: 'Dhaka - Kathmandu - Dhaka air ticket by Himalayan air, 2 nights twin share accommodation in Kathmandu at Hotel Royal Suite (3 star),2 nights twin share accommodation in Pokhara at hotel Dandelion (3 star), daily breakfast, taxes & service charge, airport – hotel – airport transfers, Kathmandu-Pokhara-Kathkandu transfer (seat in coach basis) with lunch box and Kathmandu & Pokhara half day sightseeing as per itinerary.', img: 'https://i.ibb.co/P4DL22q/Collage-of-popular-Nepalese-travel-destinations-Kathmandu-valley-and-Himalaya-mountains-Begnas-Tal-N.jpg' },
    { tourTitle: 'The Royal Tulip Cox’s Bazar', price: '10,000', package_states: 'pending', description: 'The Royal Tulip Cox’s Bazar provides two swimming pools, one exclusively for ladies. The resort boasts of a plethora of indoor & outdoor activities for both adults and kids which include an internationally acclaimed water park, tennis & badminton courts, 3D movie hall, billiards, amphitheater, a luxurious spa and a well-appointed gym.The Royal Tulip Cox’s Bazar also offers a stunning range of Banqueting & Conferencing options for all your needs. Our selection of restaurants and bars will leave you spoilt for choice with 5 specialty restaurants, a multi-cuisine all day dining with indoor & alfresco seating, 2 well-stocked bars & lounge, an ice cream parlor and a juice bar.', img: 'https://i.ibb.co/xDMgygB/cox-bazar.jpg' },
    {
        tourTitle: 'Sajek valley', package_states: 'pending', price: '7,000', description: 'Sajek valley is 2000 feet above sea level. Sajek valley is known as the Queen of Hills & Roof of Rangamati.The name of Sajek Valley came from Sajek River that originates from Karnafuli river.Sajek river is working as a border between Bangladesh and India. Sajek valley resorts are made on the side of the hill to provide the unique experience of tribal lifestyle.', img: 'https://i.ibb.co/JRhdmyK/sajec.jpg'
    },

]